apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello.name" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "hello.selectorLabels" . | nindent 4 }}
